name: create new branch

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout dev
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Create new Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b release
          git push origin release
