name: create new branch

on:
  schedule:
    - cron: '0 0 * * 7'  # At 09:00 on Sunday(JST).

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout dev
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Create new Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b release
          git push origin release
