name: create new branch

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout dev
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Create new Branch
        env:
          TZ: 'Asia/Tokyo'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=`date +"%Y%m%d"`
          BRANCH_NAME="release_$DATE"
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"
