name: merge-notification
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types: [open]

jobs:
  slackNotification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: '本番リリース通知'
          SLACK_ICON: 'https://user-images.githubusercontent.com/25860930/178177446-1494100d-a954-447f-af83-f769b4d709e1.png'
          SLACK_MESSAGE: 「${{ github.event.pull_request.title }}」を本番リリースしました！
